@BASE_URL = http://localhost:8899

@UserToken = {{userLogin.response.body.token}}

###
GET {{BASE_URL}}/check

###
POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
  "username": "ppscc1012",
  "email": "ppscc1012@gmail.com",
  "firstName": "Nantana",
  "lastName": "Santaweesuk",
  "password": "12345678",
  "confirmPassword": "12345678"
}

###
# @name userLogin
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{

  "identity": "ppscc1012",
  "password": "12345678"
}

###
# @name getMe
GET {{BASE_URL}}/auth/me
Authorization: Bearer {{UserToken}}